devcontainer:
  outputs:
    devcontainer:
      type: postgres
      threads: 1
      host: warehouse
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: analytics
  target: devcontainer